server:
  address: ${server-address:0.0.0.0}
  port: ${server-port:8080}

logging:
  config: classpath:logback-spring-prod.xml
  level:
    root: INFO

nacos:
  config:
    server-addr: ${nacos-address:192.168.0.126}:${nacos-port:8848}
    namespace: zt-payment-prod
    group: ms-wechatv3

spring:
  application:
    name: wechatapi-v3
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${nacos-address:192.168.0.126}:${nacos-port:8848}
        service: ms-wechatv3
        namespace: zt-payment-prod
        group: zt-payment
        ip: ${nacos-discovery-ip:${server.address}}
        port: ${nacos-discovery-port:${server.port}}
  datasource:
    url: jdbc:mysql://10.0.17.201:3306/pay
    username: pay
    password: 75sJNqCv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false


